name: Braden East
description: Stellar design at warp speed
year: 2024
email: braden@bartiancreative.com
root: https://bradeneast.com
netlify_site_id: a398d413-5c2c-430f-8318-8a3add053a22
socials:
  Dribbble: //dribbble.com/bradeneast
  Github: //github.com/bradeneast