[build]
command = "curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno task build --location=https://bradeneast.com"
publish = "_site"

[dev]
autoLaunch = true
command = "lume --serve"
framework = "#custom"
port = 8888
publish = "_site"
targetPort = 3000

[[redirects]]
from = "/*"
status = 404
to = "/404"

[[redirects]]
force = true
from = "https://bradeneast.netlify.app"
status = 301
to = "https://bradeneast.com"
