[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
exclude = [
  '**/404/*',
  '**/random/*',
]

[[redirects]]
from = "/*"
status = 404
to = "/404/"

[[redirects]]
from = "/"
status = "301"
to = "/about/"
