[build]
command = "curl -fsSL https://deno.land/install.sh | sh && /opt/buildhome/.deno/bin/deno task build"
publish = "_site"

[dev]
autoLaunch = true
command = "deno task lume --serve"
framework = "#custom"
port = 8888
publish = "_site"
targetPort = 3000

[[redirects]]
from = "/*"
status = 404
to = "/404"

[[redirects]]
from = "/PYWOK-colors"
status = 301
to = "https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=&foreground-colors=%23000000%2C%20Black%0D%0A%23002E5C%2C%20Water%20Blue%20-%20Dark%0D%0A%230066a6%2C%20Sky%20Blue%20-%20Dark%0D%0A%231B9FD5%2C%20Sky%20Blue%20-%20Bright%0D%0A%23b2aeaa%2C%20Warm%20Grey%0D%0A%23FFFFFF%2C%20White&es-color-form__tile-size=large&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18"
