[build]
command = "curl -fsSL https://deno.land/install.sh | sh && /opt/buildhome/.deno/bin/deno task build"
publish = "_site"

[dev]
autoLaunch = true
command = "deno task lume --serve"
framework = "#custom"
port = 8888
publish = "_site"
targetPort = 3000

[[redirects]]
from = "/*"
status = 404
to = "/404"
