[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
exclude = [
  '**/404/*',
  '**/random/*',
]

#############
# REDIRECTS #
#############

[[redirects]]
from = "/"
status = 301
to = "/about/"

[[redirects]]
Role = ["admin"]
force = true
from = "/admin/*"
status = 200

[[redirects]]
force = true
from = "/admin/*"
status = 401
to = "/admin/login"

[[redirects]]
from = "/*"
status = 404
to = "/404/"
